# Generated by Django 5.1.3 on 2024-11-24 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('UserName', models.CharField(max_length=100)),
                ('Status', models.CharField(default='Unregistered', max_length=100)),
                ('Email', models.EmailField(max_length=100)),
                ('Text', models.TextField(default='No text', max_length=5000)),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('HomePage', models.URLField(max_length=100, null=True)),
                ('CAPTCHA', models.CharField(default='No CAPTCHA', max_length=100)),
                ('Password', models.CharField(default='User does`t have a password', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Created', models.DateTimeField(auto_now_add=True, null=True)),
                ('Text', models.TextField(default='No text', max_length=5000)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.user')),
            ],
        ),
    ]
