# Generated by Django 5.1.3 on 2024-11-26 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Date',
            new_name='RegisterDate',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Text',
        ),
        migrations.AlterField(
            model_name='user',
            name='Status',
            field=models.CharField(default='Registered', max_length=100),
        ),
        migrations.RenameModel(
            old_name='Comments',
            new_name='Post',
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Created', models.DateTimeField(auto_now_add=True, null=True)),
                ('Text', models.TextField(default='No text', max_length=5000)),
                ('Post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.post')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.user')),
            ],
        ),
    ]
