version: "3.9"
services:
  web:
    build: .
    ports:
      - "8000:5000"
    command: python manage.py runserver
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
  db:
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    hostname: db

